### ISSUE TITLE
Duplicate Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by sergiors** [jdesrosiers/silex-cors-provider#13]
Hi, I'm using Backbone and Silex, but when I put `'cors.allowOrigin' => 'http://manager-spa.inbep.com.br'` and do a request with Backbone, it happens:

`The 'Access-Control-Allow-Origin' header contains multiple values 'http://manager-spa.inbep.com.br, *', but only one is allowed.`

Do you know why this happens?

**Comment by jdesrosiers** [comment]
Looks like a bug.  What version are you running?

**Comment by sergiors** [comment]
```{
        "silex/silex": "~1.2",
        "doctrine/orm": "~2.4",
        "fzaninotto/faker": "~1.4",
        "symfony/validator": "~2.6",
        "dflydev/doctrine-orm-service-provider": "~1.0",
        "jdesrosiers/silex-cors-provider": "~0.1"
    }
```

**Comment by jdesrosiers** [comment]
I'm not able to reproduce the error.  Is it possible that some other middleware in your project is trying to set the `Access-Control-Allow-Origin` header?  silex-cors-provider should never set `*`, so I'm guessing something else might be doing that.

**Comment by sergiors** [comment]
you are right! the nginx added the *
