### ISSUE TITLE
Compatibility with Symfony routing 2.7.x

### ISSUE THREAD

**Issue by cyberwolf** [jdesrosiers/silex-cors-provider#15]
Hi,

I tried upgrading to Symfony routing component 2.7 but the cors provider causes some Deprecated PHP notices:

> Deprecated: The "_method" requirement is deprecated since version 2.2 and will be removed in 3.0.
> Use the setMethods() method instead or the "methods" option in the route definition.

**Comment by jdesrosiers** [comment]
Use of "_method" was removed in version 0.1.2.  The latest version is 0.1.3.  I think you just need to update to the latest version.

**Comment by cyberwolf** [comment]
Hi Jason,

I am using version 0.1.3. Will take a closer look to what exactly is triggering the error and get back to you.

**Comment by cyberwolf** [comment]
I submitted a pull request: #16

**Comment by jdesrosiers** [comment]
I see what was happening now.  Thanks for figuring it out.
