### ISSUE TITLE
Not working with php build in server

### ISSUE THREAD

**Issue by localgod** [jdesrosiers/silex-cors-provider#17]
If I start my skeleton app like this:
```
php -S localhost:8000
```
Serving this file:
```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

$app = new Silex\Application();
$app->register(new JDesrosiers\Silex\Provider\CorsServiceProvider(), array());
$app->after($app["cors"]);

$app->get('/', function () use($app) {
    $data = array(
        'title' => 'Hello world'
    );
    return $app->json($data);
});

$app->run(); 
```
When I access the server from my angularjs app running on `127.0.0.1:10000` I get the following error in my browser:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8000/. (Reason: CORS request failed).
```
Any hints?

**Comment by jdesrosiers** [comment]
There is nothing wrong with the code you have provided.  I created a simple static HTML page that makes a cross-origin request to the code you provided using jQuery.  Everything worked as expected.  Therefore, I suspect that the problem is in your angularjs app.  I'm not familiar enough with angularjs to setup my own test using angularjs.

**Comment by jdesrosiers** [comment]
I found a jsfiddle that I was able to modify to setup a test with angularjs.  Everything still seems to be working as expected.  Here is the code I used.

```html
<html>
  <head>
    <title>Test CORS</title>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.js"></script>
    <script>
      angular
        .module('Test', [])
        .controller('corsCtrl', function ($scope, $http) {
          $scope.useHttp = function() {
            $http
              .get('http://localhost:8000')
              .success(function(data) {
                alert(data.title);
              });
          };
        });
    </script>
  </head>
  <body>
    <div ng-app="Test">
      <div ng-controller="corsCtrl">
        <button ng-click="useHttp()">$http.get request</button>
      </div>
    </div>
  </body>
</html>
```

**Comment by localgod** [comment]
Hmmm. Your example dos not work on my setup (osx, firefox 38 and safari 8). Any idea?

**Comment by localgod** [comment]
Turns out you can not use `127.0.0.1` but `localhost` works. Strange but what can you do...
