### ISSUE TITLE
Add support for specifying the Access-Control-Allow-Headers CORS header

### ISSUE THREAD

**Issue by jdesrosiers** [jdesrosiers/silex-cors-provider#2]
As far as I know, the `CorsServiceProvider` can support all features in the `CORS` specification except one `Access-Control-Allow-Headers`.  It cheats by hardcoding this header `*`.  For this service to be complete, it needs to all the user to specify a value for `Access-Control-Allow-Headers`.

**Comment by herbertpimentel** [comment]
+1 I also need that.

**Comment by jdesrosiers** [comment]
@herbertpimentel, I'll look into it, but it will be at least a few weeks before I have the time.

**Comment by jdesrosiers** [comment]
It's been a while, but I finally went back and added this functionality.
