### ISSUE TITLE
Cors: make isCorsRequest() and isPreflightRequest() methods public

### ISSUE THREAD

**Issue by MacDada** [jdesrosiers/silex-cors-provider#22]
Hi,

I need to use `isCorsRequest()` and `isPreflightRequest()` in my code, outside of the `Cors` class.
I could just copy–paste them, but it would be nice to just reuse existing implementation.

BTW, we could make them static, as they don't contain any object state logic.

**Comment by jdesrosiers** [comment]
Do you mind sharing what it is you need access to these functions for?

**Comment by MacDada** [comment]
> Do you mind sharing what it is you need access to these functions for?

@jdesrosiers I have a filter that validates the right app that is "talking" to my REST(y) API. It must ignore preflight requests, as browsers don't send them:

        $app->before(function(Request $request) use ($app) {
            $apiClient = $request->headers->get('X-Api-Client');

            if (!in_array($apiClient, $app['valid_api_clients'])
                && !(isset($app['cors']) && $app['cors']->isPreflightRequest($request))
            ) {
                return new JsonResponse(['api_client' => 'access_denied'], 403);
            }
        }, App::EARLY_EVENT);

**Comment by MacDada** [comment]
So, to be precise, I only need `isPreflightRequest()`, but I thought that it would be useful to use `isCorsRequest()` as well.

**Comment by jdesrosiers** [comment]
Closing issue because we are taking another approach.  See #24
