### ISSUE TITLE
What about a release 1.0.0 ?

### ISSUE THREAD

**Issue by alcalyn** [jdesrosiers/silex-cors-provider#26]
At least to avoid to put `dev-master` in composer.json.

There is tags for 0.x branch, but not 1.x

**Comment by jdesrosiers** [comment]
I haven't tagged it yet because it is based on Silex 2.0 that hasn't been tagged yet.  But, I didn't think it would take this long for an official release.  I also didn't expect so many people to be using it before there was an official release.  So, I'll think about it.

**Comment by alcalyn** [comment]
Ok sure, I think that tagging 1.0.0 once Silex 2 is released is better

**Comment by alcalyn** [comment]
@jdesrosiers Silex 2 has been released, just saying :)

**Comment by alcalyn** [comment]
https://github.com/jdesrosiers/silex-cors-provider/pull/30

**Comment by jdesrosiers** [comment]
1.0.0 is now released.
