### ISSUE TITLE
405 rather than a 404 on route not found

### ISSUE THREAD

**Issue by thewilkybarkid** [jdesrosiers/silex-cors-provider#34]
`CorsServiceProvider` makes the `OPTIONS` method available for any path. If I do a `GET` request to a route that doesn't exist, Silex returns a `405 Method Not Allowed` rather than the expected `404 Not Found`.

**Comment by jdesrosiers** [comment]
Thanks for bringing this to my attention.  I'm looking into it.  It correctly handles 404 for CORS preflight requests, but I didn't realize it was giving the wrong response for non-CORS requests.

**Comment by jdesrosiers** [comment]
I just tagged a fix.  Please let me know if you have any more issues.

**Comment by thewilkybarkid** [comment]
Great, thanks for the prompt fix!
