### ISSUE TITLE
Access-Control-Expose-Headers should be comma, not space separated

### ISSUE THREAD

**Issue by vrodic** [jdesrosiers/silex-cors-provider#35]
Hello,

According to Mozilla MDN here, 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

Access-Control-Expose-Headers should be comma, not space separated. It also defaults to none, not to all. 

We've seen this when testing with Angular 2 Client on Google Chrome. The Angular 2 client doesn't see the headers we've sent (Location for example) if the list of allowed headers is not comma separated. 

You probably need to update your documentation and tests.

**Comment by jdesrosiers** [comment]
Thanks!  You're right.  I'll fix it up.

**Comment by jdesrosiers** [comment]
Done.
