### ISSUE TITLE
Is there support for Silex 1.3?

### ISSUE THREAD

**Issue by ardian-c** [jdesrosiers/silex-cors-provider#40]
I'm wondering if I can use this package with Silex 1.3? 
Thank you.

**Comment by jdesrosiers** [comment]
Yes. The 0.x releases work with Silex 1.x while the 1.x releases work with Silex 2.x. Version `0.6.0` is the latest release that works with Silex 1.x.

**Comment by ardian-c** [comment]
I understand, thank you :)
